# Generated by Django 4.2.5 on 2023-10-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menuitem_menu_name_remove_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
